version: "3"
services:
  mongo:
    image: mongo:6.0
    container_name: opa_chat_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwordroot
    volumes:
      - mongo-data:/data/db
    networks:
      - opa_chat

  mongo-express:
    image: mongo-express:1.0.0
    container_name: opa_chat_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: passwordroot
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - opa_chat

  nginx:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - opa_chat

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - opa_chat

  api:
    image: node:20.18.0
    working_dir: /app
    ports:
      - 3000
    volumes:
      - ./api:/app
    command: sh -c "npm i --silent && npm run dev"
    depends_on:
      - mongo
    networks:
      - opa_chat
    deploy:
      replicas: 3

  app:
    image: node:20.18.0
    container_name: opa_chat_app
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    privileged: true
    tty: true
    command: bash -c "npm i --silent && npm run dev"
    depends_on:
      - api
    networks:
      - opa_chat

volumes:
  mongo-data:

networks:
  opa_chat:
    driver: bridge
